inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'public_suffix.gemspec'

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'test/**/*_test.rb'

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  Enabled: false
