inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'public_suffix.gemspec'

Style/EmptyLines:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  Enabled: false
