inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'public_suffix.gemspec'

Style/RescueModifier:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  Enabled: false
