language: ruby
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- ruby-head
- jruby-19mode

sudo: false
env: COVERALL=1

before_install:
- gem install bundler

notifications:
  recipients:
  - weppos@weppos.net

matrix:
  allow_failures:
  - rvm: jruby-19mode
  - rvm: ruby-head

